services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    volumes:
      - ${PROJECT_PATH:-./project}:/application
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped

  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ${PROJECT_PATH:-./project}:/application
    restart: unless-stopped
